const readStoredMaint=()=>{try{const raw=typeof localStorage==='undefined'?null:localStorage.getItem('maint');return raw?JSON.parse(raw):[]}catch{return[]}};
const logStoragePrefix='systemLogs:';
const mqttSettingsKey='mqttSettings';
const localDateKey=(date=new Date())=>`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`;
const S={data:[],alarms:[],maint:readStoredMaint(),logs:[],last:0,lastStatus:0,rpiOnline:null,client:null,soundEnabled:false,soundContext:null,cfg:{tw:60,tc:80,cw:6,cc:8}};
const $=x=>typeof document!=='undefined'?document.getElementById(x):null;
const safeText=(id,text)=>{const el=$(id);if(el)el.textContent=text;};
const asNumber=v=>{const n=Number(v);return Number.isFinite(n)?n:null};
const sensorModel={Temperature:'DS18B20',Current:'ACS172',Vibration:'SW-420'};
const sensorName=sensor=>`${sensor} (${sensorModel[sensor]||'unknown sensor'})`;
let selectedLogDate=localDateKey();
function setLogStorageMessage(message,isError=false){const el=$('logStorageMessage');if(el){el.textContent=message;el.className=isError?'error':'muted'}}
function renderLogs(){const list=$('logList');if(list){list.replaceChildren();S.logs.forEach(entry=>{const row=document.createElement('div');row.textContent=entry;list.appendChild(row)})}setLogStorageMessage('Logs are saved on this browser for each day.')}
function loadLogsForDate(date){selectedLogDate=date;const input=$('logDate');if(input)input.value=date;try{const raw=localStorage.getItem(logStoragePrefix+date);const entries=raw?JSON.parse(raw):[];if(!Array.isArray(entries)||!entries.every(entry=>typeof entry==='string'))throw new Error('Stored daily log has an invalid format.');S.logs=entries;renderLogs()}catch(error){S.logs=[];renderLogs();setLogStorageMessage('Could not read saved logs: '+error.message,true);console.error('Could not read saved daily logs:',error)}}
function log(l,m){const now=new Date();const day=localDateKey(now);const entry=`[${now.toLocaleString()}] [${l}] ${m}`;try{const key=logStoragePrefix+day;const raw=localStorage.getItem(key);const entries=raw?JSON.parse(raw):[];if(!Array.isArray(entries)||!entries.every(item=>typeof item==='string'))throw new Error('Stored daily log has an invalid format.');entries.unshift(entry);localStorage.setItem(key,JSON.stringify(entries));if(day===selectedLogDate){S.logs=entries;renderLogs()}else setLogStorageMessage(`New log saved for ${day}. Select that date to view it.`)}catch(error){if(day===selectedLogDate){S.logs.unshift(entry);renderLogs()}setLogStorageMessage('Could not save logs in this browser: '+error.message,true);console.error('Could not save daily logs:',error)}}
function st(v,w,c){const n=asNumber(v);if(n===null)return 'UNKNOWN';return n>=c?'CRITICAL':n>=w?'WARNING':'NORMAL'} function cls(x){return String(x||'').toLowerCase()}
function cfg(){for(const k of ['tw','tc','cw','cc']){const el=$(`${k}`);if(el)S.cfg[k]=+el.value}}
function normalizeMqttUrl(value){const input=value.trim();if(!input)throw new Error('Enter your broker WebSocket URL or HiveMQ Cloud hostname.');let url;try{url=new URL(/^[a-z][a-z\d+.-]*:\/\//i.test(input)?input:`wss://${input}`)}catch{throw new Error('Enter a valid broker hostname or WebSocket URL.')}if(!['ws:','wss:'].includes(url.protocol))throw new Error('Browser MQTT requires a ws:// or wss:// URL.');if(url.username||url.password)throw new Error('Enter broker credentials in the Username and Password fields, not in the URL.');if(url.hostname.endsWith('.hivemq.cloud')){if(!url.port)url.port='8884';if(url.pathname==='/')url.pathname='/mqtt'}else if(!/^[a-z][a-z\d+.-]*:\/\//i.test(input))throw new Error('For this broker, enter the full ws:// or wss:// URL.');return url.toString()}
function loadMqttSettings(){try{const settings=JSON.parse(localStorage.getItem(mqttSettingsKey)||'{}');for(const [key,id] of [['url','mqttUrl'],['username','mqttUser'],['dataTopic','dataTopic'],['statusTopic','statusTopic']]){const field=$(id);if(field&&typeof settings[key]==='string')field.value=settings[key]}}catch(error){log('ERROR','Could not load MQTT settings: '+error.message)}}
function saveMqttSettings(){try{localStorage.setItem(mqttSettingsKey,JSON.stringify({url:($('mqttUrl')||{value:''}).value.trim(),username:($('mqttUser')||{value:''}).value.trim(),dataTopic:($('dataTopic')||{value:''}).value.trim(),statusTopic:($('statusTopic')||{value:''}).value.trim()}))}catch(error){log('ERROR','Could not save MQTT settings: '+error.message)}}
function writeMaint(){try{if(typeof localStorage!=='undefined')localStorage.setItem('maint',JSON.stringify(S.maint));}catch{return}}
function parseVibration(value){if(value===0||value===false)return 0;if(value===1||value===true)return 1;if(typeof value==='string'){const normalized=value.trim().toLowerCase();if(normalized==='0'||normalized==='false')return 0;if(normalized==='1'||normalized==='true')return 1}return null}
function add(d,source='MQTT'){if(!d||typeof d!=='object'){log('ERROR','MQTT DATA ERROR: invalid or missing data');return}const temperature=asNumber(d.temperature);const current=asNumber(d.current);const vibration=parseVibration(d.vibration);if(temperature===null||current===null||vibration===null){log('ERROR','MQTT DATA ERROR: invalid or missing data; SW-420 vibration must be 0 or 1');return}cfg();S.data.push({timestamp:d.timestamp||new Date().toISOString(),temperature,current,vibration,source});if(S.data.length>500)S.data.shift();S.last=Date.now();metrics(S.data.at(-1));charts(S.data.at(-1));history();health();alarms(S.data.at(-1))}
function metrics(d){[['temp',d.temperature,S.cfg.tw,S.cfg.tc,'tempState'],['current',d.current,S.cfg.cw,S.cfg.cc,'currentState']].forEach(x=>{const value=asNumber(x[1]);if(value===null)return;const el=$(x[0]);if(el)el.textContent=value.toFixed(2);const q=st(value,x[2],x[3]);const stateEl=$(x[4]);if(stateEl){stateEl.textContent=q;stateEl.className=cls(q)}});const vibration=$('vibration');if(vibration){vibration.textContent=d.vibration?'DETECTED':'CLEAR';vibration.className=d.vibration?'warning':'normal'}const vibrationState=$('vibrationState');if(vibrationState){vibrationState.textContent=d.vibration?'VIBRATION DETECTED':'NO VIBRATION';vibrationState.className=d.vibration?'warning':'normal'}}
function notifyAlarmEmail(alarm){const field=$('emailApiUrl');const baseUrl=field?field.value.trim().replace(/\/+$/,''):'';if(!baseUrl){log('WARN','Alarm email not sent: configure the Alarm API URL in Settings');return}let endpoint;try{endpoint=new URL(baseUrl);if(!['http:','https:'].includes(endpoint.protocol))throw new Error('URL must use HTTP or HTTPS');endpoint.pathname=endpoint.pathname.replace(/\/+$/,'')+'/api/alarms/email';endpoint.search='';endpoint.hash=''}catch(error){log('ERROR','Invalid Alarm API URL: '+error.message);return}if(typeof fetch!=='function'){log('ERROR','Alarm email not sent: browser fetch is unavailable');return}fetch(endpoint.toString(),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({sensor:alarm.sensor,model:sensorModel[alarm.sensor],value:alarm.value,threshold:alarm.threshold,severity:alarm.severity,timestamp:alarm.timestamp})}).then(response=>{if(!response.ok)throw new Error(`API returned HTTP ${response.status}`);log('INFO',`Alarm email sent for ${sensorName(alarm.sensor)} (${alarm.severity})`)}).catch(error=>log('ERROR',`Alarm email delivery failed for ${sensorName(alarm.sensor)}: ${error.message}`))}
function setAlarmSoundStatus(message,isError=false){const status=$('alarmSoundStatus');if(status){status.textContent=message;status.className=isError?'error':'muted'}const button=$('alarmSoundToggle');if(button){button.textContent=S.soundEnabled?'Disable alarm sound':'Enable alarm sound';button.setAttribute('aria-pressed',String(S.soundEnabled))}}
function playAlarmSound(){if(!S.soundEnabled||!S.soundContext||S.soundContext.state!=='running')return;const now=S.soundContext.currentTime;[880,660].forEach((frequency,index)=>{const start=now+index*.28;const oscillator=S.soundContext.createOscillator();const gain=S.soundContext.createGain();oscillator.type='sine';oscillator.frequency.setValueAtTime(frequency,start);gain.gain.setValueAtTime(.0001,start);gain.gain.exponentialRampToValueAtTime(.18,start+.02);gain.gain.setValueAtTime(.18,start+.14);gain.gain.exponentialRampToValueAtTime(.0001,start+.2);oscillator.connect(gain);gain.connect(S.soundContext.destination);oscillator.start(start);oscillator.stop(start+.21)})}
async function toggleAlarmSound(){if(S.soundEnabled){S.soundEnabled=false;setAlarmSoundStatus('Alarm sound is off.');return}try{const AudioContextClass=window.AudioContext||window.webkitAudioContext;if(!AudioContextClass){setAlarmSoundStatus('This browser does not support alarm sound.',true);log('ERROR','Alarm sound is not supported by this browser');return}if(!S.soundContext)S.soundContext=new AudioContextClass();if(S.soundContext.state!=='running')await S.soundContext.resume();if(S.soundContext.state!=='running')throw new Error('Audio permission was not granted');S.soundEnabled=true;setAlarmSoundStatus('Alarm sound enabled. A test tone will play now.');playAlarmSound()}catch(error){S.soundEnabled=false;setAlarmSoundStatus('Could not enable alarm sound: '+error.message,true);log('ERROR','Could not enable alarm sound: '+error.message)}}
const alarmSoundToggle=$('alarmSoundToggle');if(alarmSoundToggle)alarmSoundToggle.onclick=toggleAlarmSound;
function createAlarm(sensor,value,threshold,severity,key){const now=new Date();const alarm={key,time:now.toLocaleString(),timestamp:now.toISOString(),sensor,value,threshold,severity,status:'ACTIVE'};S.alarms.unshift(alarm);const displayValue=typeof value==='number'?value.toFixed(2):value;const displayThreshold=typeof threshold==='number'?threshold.toFixed(2):threshold;log(severity,`${sensorName(sensor)} threshold exceeded: value ${displayValue}, threshold ${displayThreshold}`);notifyAlarmEmail(alarm);return alarm}
function alarms(d){let hasNewAlarm=false;[['Temperature',d.temperature,S.cfg.tw,S.cfg.tc],['Current',d.current,S.cfg.cw,S.cfg.cc]].forEach(x=>{let q=st(x[1],x[2],x[3]);if(q==='NORMAL')return;let key=x[0]+q;if(!S.alarms.some(a=>a.key===key&&a.status!=='RESOLVED')){createAlarm(x[0],x[1],q==='CRITICAL'?x[3]:x[2],q,key);hasNewAlarm=true}});if(d.vibration){const key='VibrationWARNING';if(!S.alarms.some(a=>a.key===key&&a.status!=='RESOLVED')){createAlarm('Vibration','DETECTED','Detection','WARNING',key);hasNewAlarm=true}}if(hasNewAlarm)playAlarmSound();renderAlarms();latest()}
function renderAlarms(){const el=$('alarmTable');if(!el)return;el.innerHTML=S.alarms.map((a,i)=>`<tr><td>${a.time}</td><td>${sensorName(a.sensor)}</td><td>${typeof a.value==='number'?a.value.toFixed(2):a.value}</td><td>${a.threshold}</td><td class="${cls(a.severity)}">${a.severity}</td><td>${a.status}</td><td><button onclick="act(${i})">${a.status==='ACTIVE'?'ACK':'RESOLVE'}</button></td></tr>`).join('')||'<tr><td colspan=7>No alarms</td></tr>'}
function act(i){if(!S.alarms[i])return;S.alarms[i].status=S.alarms[i].status==='ACTIVE'?'ACKNOWLEDGED':'RESOLVED';renderAlarms();latest()}function latest(){let a=S.alarms.find(x=>x.status!=='RESOLVED');const el=$('latestAlarm');if(!el)return;el.innerHTML=a?`${sensorName(a.sensor)} — <b class="${cls(a.severity)}">${a.severity}</b><br>${typeof a.value==='number'?a.value.toFixed(2):a.value} / ${a.threshold}`:'No active alarms'}
function history(){const searchEl=$('historySearch');const tableEl=$('historyTable');if(!tableEl)return;const q=(searchEl?searchEl.value:'').toLowerCase();tableEl.innerHTML=S.data.slice().reverse().filter(x=>JSON.stringify(x).toLowerCase().includes(q)).slice(0,100).map(x=>`<tr><td>${new Date(x.timestamp).toLocaleString()}</td><td>${Number(x.temperature).toFixed(2)}</td><td>${Number(x.current).toFixed(2)}</td><td>${x.vibration?'DETECTED':'CLEAR'}</td><td>${x.source}</td></tr>`).join('')}
function health(){let d=S.data.at(-1);if(!d)return;let n=100;[['temperature',d.temperature,S.cfg.tw,S.cfg.tc],['current',d.current,S.cfg.cw,S.cfg.cc]].forEach(x=>{const value=asNumber(x[1]);if(value===null)return;if(value>=x[3])n-=30;else if(value>=x[2])n-=15});if(d.vibration)n-=25;n=Math.max(0,n);const healthValue=$('healthValue');const healthState=$('healthState');const machineState=$('machineState');if(healthValue)healthValue.textContent=n;let q=n<50?'CRITICAL':n<80?'WARNING':'GOOD';if(healthState){healthState.textContent=q;healthState.className=cls(q)};if(machineState){machineState.textContent=q==='GOOD'?'NORMAL':q;machineState.className='state '+cls(q)}}
const C={};function mk(id){const canvas=$(id);if(!canvas||typeof Chart==='undefined')return null;const vibration=id.toLowerCase().includes('vibration');const temperature=id.toLowerCase().includes('temp');const current=id.toLowerCase().includes('current');return new Chart(canvas,{type:temperature?'bar':'line',data:{labels:[],datasets:[{label:vibration?sensorName('Vibration'):temperature?sensorName('Temperature'):current?sensorName('Current'):id,data:[],tension:.2,stepped:vibration,backgroundColor:temperature?'rgba(74,168,255,.55)':undefined,borderColor:temperature?'#4aa8ff':undefined,borderWidth:temperature?1:undefined}]},options:{responsive:true,animation:false,plugins:{legend:{display:false}},scales:{x:{ticks:{color:'#8d9aa7'}},y:{min:vibration?0:undefined,max:vibration?1:undefined, ticks:{stepSize:vibration?1:undefined,color:'#8d9aa7',callback:vibration?(value=>value===1?'Detected':'Clear'):undefined}}}}})}
function init(){['tempChart','liveTemp'].forEach(x=>{const chart=mk(x);if(chart)C[x]=chart});['currentChart','liveCurrent'].forEach(x=>{const chart=mk(x);if(chart)C[x]=chart});['vibrationChart','liveVibration'].forEach(x=>{const chart=mk(x);if(chart)C[x]=chart})}
function charts(d){[['tempChart','liveTemp',d.temperature],['currentChart','liveCurrent',d.current],['vibrationChart','liveVibration',d.vibration]].forEach(x=>x.slice(0,2).forEach(k=>{let c=C[k];if(!c||!c.data||!c.data.labels||!c.data.datasets)return;c.data.labels.push(new Date(d.timestamp).toLocaleTimeString());c.data.datasets[0].data.push(x[2]);if(c.data.labels.length>40){c.data.labels.shift();c.data.datasets[0].data.shift()}c.update()}))}
function setMqttMessage(message,isError=false){const el=$('mqttMessage');if(el){el.textContent=message;el.className=isError?'error':'muted'}}
function setRpiStatus(online){S.rpiOnline=online;S.lastStatus=Date.now();const badge=$('rpiState');if(badge){badge.textContent=online?'RPI ONLINE':'RPI OFFLINE';badge.className='badge '+(online?'on':'off')}const value=$('sysRpi');if(value)value.textContent=online?'ONLINE':'OFFLINE'}
function processStatus(payload){let value;try{value=JSON.parse(payload)}catch{value=payload.trim()}let status=value;if(value&&typeof value==='object'){status=value.rpi??value.raspberryPi??value.online??value.status??value.state}if(typeof status==='string'){const normalized=status.toLowerCase();if(['online','connected','true','1','up','running'].includes(normalized))setRpiStatus(true);else if(['offline','disconnected','false','0','down','stopped'].includes(normalized))setRpiStatus(false);else{log('WARN','Unrecognized Raspberry Pi status message');return}}else if(typeof status==='boolean'||typeof status==='number')setRpiStatus(Boolean(status));else{log('WARN','MQTT status message has no recognized status value');return}log('INFO','Raspberry Pi status: '+(S.rpiOnline?'ONLINE':'OFFLINE'))}
function connect(){cfg();const url=($('mqttUrl')||{value:''}).value.trim();const dataTopic=($('dataTopic')||{value:''}).value.trim();const statusTopic=($('statusTopic')||{value:''}).value.trim();if(!url){setMqttMessage('Enter the broker WebSocket URL to connect.',true);log('ERROR','MQTT WebSocket URL is empty');return}let parsedUrl;try{parsedUrl=new URL(url)}catch{setMqttMessage('Enter a valid ws:// or wss:// broker URL.',true);log('ERROR','Invalid MQTT WebSocket URL');return}if(!['ws:','wss:'].includes(parsedUrl.protocol)){setMqttMessage('Browser MQTT requires a ws:// or wss:// URL.',true);log('ERROR','MQTT URL must use ws:// or wss://');return}if(!dataTopic||!statusTopic){setMqttMessage('Enter both the sensor data topic and status topic.',true);log('ERROR','MQTT data and status topics are required');return}if(typeof mqtt==='undefined'||!mqtt.connect){setMqttMessage('MQTT library failed to load. Check the network and reload.',true);log('ERROR','MQTT library is unavailable');return}if(S.client&&typeof S.client.end==='function')S.client.end(true);setMqttMessage('Connecting to broker…');conn(false);S.rpiOnline=null;S.lastStatus=0;try{const client=mqtt.connect(url,{username:($('mqttUser')||{value:''}).value,password:($('mqttPass')||{value:''}).value,clientId:'web-'+Math.random().toString(16).slice(2),reconnectPeriod:3000,connectTimeout:10000,clean:true});S.client=client;client.on('connect',()=>{if(S.client!==client)return;conn(true);setMqttMessage('Connected. Waiting for sensor data and Raspberry Pi status.');log('INFO','MQTT connected');[[dataTopic,'sensor data'],[statusTopic,'device status']].forEach(([topic,label])=>client.subscribe(topic,{qos:0},(error)=>{if(error){log('ERROR','MQTT subscription failed for '+label+': '+error.message);setMqttMessage('Connected, but subscribing to '+label+' failed.',true)}else log('INFO','Subscribed to '+label+' topic')}))});client.on('message',(topic,message)=>{const payload=message.toString();if(topic===dataTopic){try{const data=JSON.parse(payload);add(data)}catch{log('ERROR','Invalid JSON received on sensor data topic')}}else if(topic===statusTopic)processStatus(payload)});client.on('reconnect',()=>{if(S.client===client){conn(false);setMqttMessage('Connection lost; reconnecting…');log('WARN','MQTT reconnecting')}});client.on('offline',()=>{if(S.client===client){conn(false);setMqttMessage('Broker connection is offline.',true)}});client.on('close',()=>{if(S.client===client){conn(false);setMqttMessage('Broker connection closed.',true)}});client.on('error',error=>{if(S.client===client){log('ERROR','MQTT '+error.message);setMqttMessage('MQTT connection error: '+error.message,true)}})}catch(error){S.client=null;conn(false);setMqttMessage('Could not start MQTT connection: '+error.message,true);log('ERROR','Could not start MQTT connection: '+error.message)}}
function connectWithMqttSettings(){const urlField=$('mqttUrl');if(!urlField){log('ERROR','MQTT URL input was not found');return}try{urlField.value=normalizeMqttUrl(urlField.value);saveMqttSettings();connect()}catch(error){setMqttMessage(error.message,true);log('ERROR','Invalid MQTT broker URL: '+error.message)}}
function conn(ok){const mqttState=$('mqttState');if(mqttState){mqttState.textContent=ok?'MQTT ONLINE':'MQTT OFFLINE';mqttState.className='badge '+(ok?'on':'off')}const sysMqtt=$('sysMqtt');if(sysMqtt)sysMqtt.textContent=ok?'ONLINE':'OFFLINE'}
function disconnect(){const client=S.client;S.client=null;if(client&&typeof client.end==='function')client.end(true);conn(false);setMqttMessage('Disconnected from broker.');log('INFO','MQTT disconnected')}
loadMqttSettings();['mqttUrl','mqttUser','dataTopic','statusTopic'].forEach(id=>{const field=$(id);if(field)field.addEventListener('change',saveMqttSettings)});const connectBtn=$('connectBtn');if(connectBtn)connectBtn.onclick=connectWithMqttSettings;const disconnectBtn=$('disconnectBtn');if(disconnectBtn)disconnectBtn.onclick=disconnect;const historySearch=$('historySearch');if(historySearch)historySearch.oninput=history;
const emailApiUrlField=$('emailApiUrl');if(emailApiUrlField){try{emailApiUrlField.value=localStorage.getItem('emailApiUrl')||''}catch(error){log('ERROR','Could not load Alarm API URL: '+error.message)}emailApiUrlField.onchange=()=>{try{localStorage.setItem('emailApiUrl',emailApiUrlField.value.trim());log('INFO','Alarm API URL saved')}catch(error){log('ERROR','Could not save Alarm API URL: '+error.message)}}}
const saveMaint=$('saveMaint');if(saveMaint){saveMaint.onclick=()=>{S.maint.push({date:($('maintDate')||{value:''}).value||new Date().toISOString().slice(0,10),machine:($('maintMachine')||{value:''}).value,type:($('maintType')||{value:''}).value,desc:($('maintDesc')||{value:''}).value});writeMaint();const maintDesc=$('maintDesc');if(maintDesc)maintDesc.value='';renderMaint();log('INFO','Maintenance saved')}};
function renderMaint(){const el=$('maintList');if(!el)return;el.innerHTML=S.maint.slice().reverse().map(x=>`<div style="padding:10px;border-bottom:1px solid #26313C">${x.date} — ${x.type} — ${x.machine}<br>${x.desc}</div>`).join('')||'No maintenance events.'}
const navButtons=document.querySelectorAll?document.querySelectorAll('.nav'):[];navButtons.forEach&&navButtons.forEach(b=>b.onclick=()=>{document.querySelectorAll('.nav').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));const page=$(b.dataset.page);if(page)page.classList.add('active');const pageTitle=$('pageTitle');if(pageTitle)pageTitle.textContent=b.textContent});
const logDateInput=$('logDate');if(logDateInput){logDateInput.max=localDateKey();logDateInput.onchange=()=>{if(logDateInput.value)loadLogsForDate(logDateInput.value)}}loadLogsForDate(selectedLogDate);
setInterval(()=>{const clock=$('clock');if(clock)clock.textContent=new Date().toLocaleString();if(S.lastStatus&&Date.now()-S.lastStatus>15000)setRpiStatus(false);else if(!S.lastStatus)setRpiStatus(false);const sysData=$('sysData');if(sysData)sysData.textContent=S.data.length?new Date(S.data.at(-1).timestamp).toLocaleString():'--'},1000);
init();renderMaint();renderAlarms();history();log('INFO','Application initialized');